### ISSUE TITLE
Why webpack throw an warning when I use require.ensure and require.context?

### ISSUE THREAD

**Issue by mrdulin** [webpack-contrib/bundle-loader#32]
```js
//Warning! not work
const loadComponentWithContext = (moduleName) => {
	return (nextState, cb) => {
		require.ensure([], require => {
			var reqWithCtx = require.context(`./modules/${moduleName}`, true, /\.js$/);
			var component = reqWithCtx('/index.js').default;
			console.log(component);
			cb(null, component);
		}, moduleName)
	}
};

//worked, each module is a chunk
const loadComponentWithBundleLoader = (moduleName) =>  (nextState, cb) => {
    require('bundle-loader!./modules/'+ moduleName + '/index.js')(function(module) {
        cb(null, module.default);
    });
}

//worked, but only one chunk
const loadComponent = (moduleName) => (nextState, cb) => {
	require.ensure([], require => {
		var es6Component = require(`./modules/${moduleName}/index.js`);
		cb(null, es6Component.default);
	})
}

const routes = (
	<Route path='/'>
		<IndexRoute getComponent={loadComponent('home')}></IndexRoute>
		<Route path='about' getComponent={loadComponent('about')}></Route>
		<Route path='contact' getComponent={loadComponent('contact')}></Route>
	</Route>
);
```

`loadComponentWithContext` throw an warning: 

```bash
WARNING in ./src/route.js
Critical dependencies:
46:2-9 require function is used in a way in which dependencies cannot be statically extracted
 @ ./src/route.js 46:2-9

WARNING in ./src/index.html
Module parse failed: /Users/dulin/workspace/webpack-summer/bundle-loader/react-demo-1/src/index.html Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (1:0)
    at Parser.pp.raise (/usr/local/lib/node_modules/webpack/node_modules/acorn/dist/acorn.js:920:13)
    at Parser.pp.unexpected (/usr/local/lib/node_modules/webpack/node_modules/acorn/dist/acorn.js:1483:8)
    at Parser.pp.parseExprAtom (/usr/local/lib/node_modules/webpack/node_modules/acorn/dist/acorn.js:330:12)
    at Parser.pp.parseExprSubscripts (/usr/local/lib/node_modules/webpack/node_modules/acorn/dist/acorn.js:225:19)
    at Parser.pp.parseMaybeUnary (/usr/local/lib/node_modules/webpack/node_modules/acorn/dist/acorn.js:204:17)
    at Parser.pp.parseExprOps (/usr/local/lib/node_modules/webpack/node_modules/acorn/dist/acorn.js:151:19)
    at Parser.pp.parseMaybeConditional (/usr/local/lib/node_modules/webpack/node_modules/acorn/dist/acorn.js:133:19)
    at Parser.pp.parseMaybeAssign (/usr/local/lib/node_modules/webpack/node_modules/acorn/dist/acorn.js:110:19)
    at Parser.pp.parseExpression (/usr/local/lib/node_modules/webpack/node_modules/acorn/dist/acorn.js:86:19)
    at Parser.pp.parseStatement (/usr/local/lib/node_modules/webpack/node_modules/acorn/dist/acorn.js:1753:23)
    at Parser.pp.parseTopLevel (/usr/local/lib/node_modules/webpack/node_modules/acorn/dist/acorn.js:1648:21)
    at Parser.parse (/usr/local/lib/node_modules/webpack/node_modules/acorn/dist/acorn.js:1616:17)
    at Object.parse (/usr/local/lib/node_modules/webpack/node_modules/acorn/dist/acorn.js:882:44)
    at Parser.parse (/usr/local/lib/node_modules/webpack/lib/Parser.js:902:15)
    at DependenciesBlock.<anonymous> (/usr/local/lib/node_modules/webpack/lib/NormalModule.js:104:16)
    at DependenciesBlock.onModuleBuild (/usr/local/lib/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
 @ ./src ^\.\/.*$

WARNING in ./src ^\.\/.*$
Module not found: Error: a dependency to an entry point is not allowed
 @ ./src ^\.\/.*$

WARNING in ./src ^\.\/.*$
Module not found: Error: a dependency to an entry point is not allowed
 @ ./src ^\.\/.*$
```

I saw the source code of `bundle-loader`, it wrap `require.ensure`.
How do I make `loadComponent` worked like `bundle-loader`?

**Comment by evilebottnawi** [comment]
Fixed on webpack side
